services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    stdin_open: true
    network_mode: service:db

  db:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
